import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import { Post } from '@/components/Post/Post';
import { GetStaticProps } from 'next';
import axios from 'axios';
import { PostItem } from '@/interfaces/post.interface';
//=========================================================================================================================

export default function Home({ posts }: HomeProps) {
	console.log(posts);
	return (
		<>
			<Head>
				<title>Hexfair Blog</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className={styles.content}>
				{posts && posts.map((obj, index) =>
					<Post key={index} title={obj.title} text={obj.text} imageUrl={obj.imageUrl ? obj.imageUrl : ''} />
				)}
			</div>
		</>
	);
}

export const getStaticProps: GetStaticProps<HomeProps> = async () => {

	const { data: posts } = await axios.get<PostItem[]>('http://localhost:4444/posts');

	return {
		props: {
			posts
		}
	};
};

interface HomeProps {
	posts: PostItem[];
}