import Head from 'next/head';
import styles from '@/styles/HomePage.module.scss';
import { Post } from '@/components/Post/Post';
import { GetStaticProps, NextPage } from 'next';
import axios from 'axios';
import { PostItem } from '@/interfaces/post.interface';
import { wrapper } from '@/redux/store';
import { setPosts } from '@/redux/auth/post.slice';
import React from 'react';
//=========================================================================================================================

const HomePage: NextPage<HomeProps> = ({ posts }) => {
	return (
		<>
			<Head>
				<title>Hexfair Blog</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className={styles.content}>
				{posts && posts.map((obj, index) =>
					<Post key={index} title={obj.title} text={obj.text} imageUrl={obj.imageUrl ? obj.imageUrl : ''} />
				)}
			</div>
		</>
	);
}

export const getStaticProps: GetStaticProps<HomeProps> = wrapper.getStaticProps((store) => async () => {
	try {
		const { data: posts } = await axios.get<PostItem[]>('http://localhost:4444/posts');

		store.dispatch(setPosts(posts));

		return {
			props: {
				posts
			}
		};
	} catch (err) {
		console.error(err);
		return {
			props: {
				posts: []
			}
		};
	}

});

interface HomeProps {
	posts: PostItem[];
}

export default HomePage;